git lfs: Add hooks

diff --git a/home/git/hooks/pre-push b/home/git/hooks/pre-push
--- a/home/git/hooks/pre-push
+++ b/home/git/hooks/pre-push
@@ -17,6 +17,12 @@
 # remote="$1"
 # url="$2"
 
+if [ "$(git config --bool --get lfs.disable)" != true ]; then
+    command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
+    git lfs pre-push "$@"
+fi
+
+
 zero=$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')
 
 while read -r local_ref local_oid _remote_ref remote_oid; do
